<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/5/14 0014
 * Time: 20:26
 */

class CourseCollection extends Collection{

    public function addItem(Cource $obj, $key = null)
    {
        parent::addItem($obj, $key); // TODO: Change the autogenerated stub
    }
}